export enum CityEnum {
  LIMA = 'Lima',
  AREQUIPA = 'Arequipa',
  CUSCO = 'Cusco',
  TRUJILLO = 'Trujillo',
  CHICLAYO = 'Chiclayo',
  PIURA = 'Piura',
  IQUITOS = 'Iquitos',
  HUANCAYO = 'Huancayo',
  TACNA = 'Tacna',
  CAJAMARCA = 'Cajamarca',
  PUCALLPA = 'Pucallpa',
  TUMBES = 'Tumbes',
  HUARAZ = 'Huaraz',
}
